### ISSUE TITLE
Add content to VDSL3 reference docs

### ISSUE THREAD

**Issue by rcannood** [viash-io/website#38]
* Create an index page for the Platforms (`/reference/config/platforms/index.qmd`); similar to how you can click 'Functionality' and 'Config'. It should contain something like:
      # Platforms
      
      A list of platforms to generate target artifacts for.
      
      * [Native](...)
      * [Docker](...)
      * [Nextflow VDSL3](...)
      
      **Example:**
      
      ```yaml
      platforms:
        - type: docker
          image: "bash:4.0"
        - type: native
        - type: nextflow
          directives:
            label: [lowcpu, midmem]
      ```
* Add overall example to `reference/config/platforms/native.qmd`. E.g. something like:

      **Example:**
      
      ```yaml
      platforms:
        - type: native
      ```
* Add overall example to `reference/config/platforms/docker.qmd`

      **Example:**
      
      ```yaml
      platforms:
        - type: docker
          image: "bash:4.0"
          setup:
            - type: apt
              packages: [ curl ]
      ```
* Add overall example to `reference/config/platforms/nextflow.qmd`

      **Example:**
      
      ```yaml
      platforms:
        - type: nextflow
          directives:
            label: [lowcpu, midmem]
      ```
